# Generated by Django 4.1.4 on 2022-12-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='training_description',
            field=models.TextField(default='It is the best training in the world'),
        ),
    ]
